#!/bin/bash

if [ "${SINGULARITY_NAME}" != "el7:x86_64" ]; then
    echo "Entering cmssw-el7..."
    exec cmssw-el7 --command-to-run "/bin/bash" "$0" "$@"
fi
echo "Now in cmssw-el7!"
echo "Command line: $0 $*"

if [ $# -lt 2 ]; then
    >&2 echo "usage: $(basename "$0") <x509up> <prog> [ <args> ]"
    exit 1
fi

set -e
export X509_USER_PROXY=/tmp/x509up_u$UID
cp "$1" "${X509_USER_PROXY}"
chmod 600 "${X509_USER_PROXY}"
voms-proxy-info

PROG="$2"
shift 2
exec "${PROG}" "$@"
